### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by Arwear10** [ds4owd-001/md-02-assignments-Arwear10#1]
@larnsce  @mianzg  @sskorik01

**Comment by sskorik01** [comment]
Hi, you haven't committed your code (your code in md-02a-data-visualization.qmd has not been updated on GitHub). You have to commit and push from Posit.cloud to confirm you have finished your assignment.

**Comment by Arwear10** [comment]
Hi! I commited it from posit, i just selected one file. I made it again with the other file (with same name assignment 2). Is it ok now? Thanks

**Comment by sskorik01** [comment]
Yes, it's good now. For the future, before opening the issue saying that you completed your assignment, make sure that your code is committed and pushed. You can do that by clicking on the code tab in your repository. There you will see the files and if you click on a single file, you can check if it has been updated or not. You can also see your commit messages next to the file, so if you pushed you should recognize the commit message. Finally, you can see the number of commits on the top and by clicking on this button, you can see all your different commits and therefore, all the different versions of your code. 

![Screenshot 2023-11-13 150533](https://github.com/ds4owd-001/md-02-assignments-Arwear10/assets/148224762/451a66e5-3111-42de-a14a-3b05bec35da5)
![Screenshot 2023-11-13 150554](https://github.com/ds4owd-001/md-02-assignments-Arwear10/assets/148224762/83f90539-7bbf-4624-89c2-131c86c0f896)
